export const X_SCOPES = [
  'mute.write',
  'tweet.moderate.write',
  'block.read',
  'follows.read',
  'list.write',
  'bookmark.read',
  'dm.read',
  'list.read',
  'tweet.write',
  'space.read',
  'block.write',
  'like.write',
  'like.read',
  'users.read',
  'tweet.read',
  'bookmark.write',
  'mute.read',
  'follows.write',
  'offline.access',
] as const;
